// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/CreamGreen.tsx": () => import("../components/mockups/hero-variants/CreamGreen.tsx"),
  "./components/mockups/hero-variants/NavyBlue.tsx": () => import("../components/mockups/hero-variants/NavyBlue.tsx"),
  "./components/mockups/hero-variants/NearBlackOrange.tsx": () => import("../components/mockups/hero-variants/NearBlackOrange.tsx"),
  "./components/mockups/hero-variants/WhiteIndigo.tsx": () => import("../components/mockups/hero-variants/WhiteIndigo.tsx")
};
