import { db, ucoControlsTable, ucoFrameworkMappingsTable, ucoAutomatedTestsTable } from "./index";

const UCO_CONTROLS = [
  { controlId: "UCO-AI-001", domain: "Authentication & Identity", name: "Multi-Factor Authentication for All Users", description: "Enforce MFA for all user accounts accessing systems and data.", objective: "Prevent unauthorized access through compromised credentials.", automationLevel: "full", remediationGuidance: "Enable MFA enforcement in your identity provider. Require MFA for all users, especially administrators." },
  { controlId: "UCO-AI-002", domain: "Authentication & Identity", name: "Privileged Account Controls", description: "Manage, monitor, and restrict privileged accounts with elevated permissions.", objective: "Limit blast radius of compromised administrator accounts.", automationLevel: "partial", remediationGuidance: "Audit all privileged accounts. Implement just-in-time access and require MFA for admin roles." },
  { controlId: "UCO-AI-003", domain: "Authentication & Identity", name: "Password Policy Enforcement", description: "Enforce strong password requirements including complexity, length, and rotation.", objective: "Prevent brute force and credential attacks.", automationLevel: "full", remediationGuidance: "Configure password policy in your identity provider: min 12 chars, complexity requirements, no common passwords." },
  { controlId: "UCO-AI-004", domain: "Authentication & Identity", name: "Single Sign-On / Identity Provider", description: "Centralize authentication through a managed identity provider.", objective: "Centralize access control and enable consistent policy enforcement.", automationLevel: "full", remediationGuidance: "Deploy an IdP (Okta, Azure AD, Google Workspace) and enforce SSO for all SaaS applications." },
  { controlId: "UCO-AC-001", domain: "Access Control", name: "Role-Based Access Control", description: "Implement RBAC to ensure users access only what their role requires.", objective: "Enforce least privilege across all systems and applications.", automationLevel: "partial", remediationGuidance: "Define roles with minimum necessary permissions. Review and enforce roles across all systems." },
  { controlId: "UCO-AC-002", domain: "Access Control", name: "Least Privilege Principle", description: "Grant minimum access required for job function.", objective: "Reduce attack surface from over-provisioned accounts.", automationLevel: "partial", remediationGuidance: "Audit permissions quarterly. Remove excessive access. Use just-in-time access for sensitive resources." },
  { controlId: "UCO-AC-003", domain: "Access Control", name: "Separation of Duties", description: "Ensure no single user can execute high-risk transactions alone.", objective: "Prevent fraud and errors through dual-control requirements.", automationLevel: "manual", remediationGuidance: "Identify critical actions requiring dual approval. Implement approval workflows." },
  { controlId: "UCO-AC-004", domain: "Access Control", name: "Periodic Access Reviews", description: "Regularly review and recertify user access rights.", objective: "Remove stale and inappropriate access over time.", automationLevel: "partial", remediationGuidance: "Schedule quarterly access reviews. Remove access for users who no longer need it." },
  { controlId: "UCO-AC-005", domain: "Access Control", name: "Offboarding & Deprovisioning", description: "Remove all access within 24 hours of employee departure.", objective: "Prevent ex-employee unauthorized access.", automationLevel: "partial", remediationGuidance: "Automate offboarding with HR system triggers. Audit for orphaned accounts monthly." },
  { controlId: "UCO-AL-001", domain: "Audit & Logging", name: "Audit Logging Enabled", description: "Enable comprehensive audit logs for all systems and user actions.", objective: "Detect security incidents and support forensic investigations.", automationLevel: "full", remediationGuidance: "Enable CloudTrail, audit logs on databases, and application logging. Centralize in SIEM." },
  { controlId: "UCO-AL-002", domain: "Audit & Logging", name: "Log Integrity & Retention", description: "Store logs securely with integrity protection for minimum 12 months.", objective: "Ensure logs are available and trustworthy for investigation.", automationLevel: "full", remediationGuidance: "Store logs in write-once storage (S3 with Object Lock). Retain for 12+ months." },
  { controlId: "UCO-AL-003", domain: "Audit & Logging", name: "Security Monitoring / SIEM", description: "Monitor logs continuously for security events and anomalies.", objective: "Detect threats in real-time before damage occurs.", automationLevel: "full", remediationGuidance: "Deploy SIEM (Splunk, Datadog, CloudWatch). Create alerts for key security events." },
  { controlId: "UCO-AL-004", domain: "Audit & Logging", name: "Alerting on Security Anomalies", description: "Generate real-time alerts for suspicious activity and policy violations.", objective: "Enable rapid response to security incidents.", automationLevel: "full", remediationGuidance: "Configure alerts for: failed logins, privilege escalation, unusual data access, off-hours activity." },
  { controlId: "UCO-CM-001", domain: "Configuration Management", name: "Version Control for All Code", description: "Store all application and infrastructure code in version control.", objective: "Enable change tracking, rollback, and collaborative code review.", automationLevel: "full", remediationGuidance: "Use Git for all code. Prohibit direct production deployments outside VCS." },
  { controlId: "UCO-CM-002", domain: "Configuration Management", name: "Code Review & Approval Process", description: "Require peer review and approval before merging code changes.", objective: "Catch security vulnerabilities before they reach production.", automationLevel: "full", remediationGuidance: "Enable branch protection. Require at least 1 reviewer. Enforce CODEOWNERS for sensitive files." },
  { controlId: "UCO-CM-003", domain: "Configuration Management", name: "Vulnerability Scanning (SAST/DAST)", description: "Automatically scan code and running applications for vulnerabilities.", objective: "Identify and remediate vulnerabilities before exploitation.", automationLevel: "full", remediationGuidance: "Integrate SAST (Semgrep, CodeQL) and dependency scanning in CI/CD pipelines." },
  { controlId: "UCO-CM-004", domain: "Configuration Management", name: "Dependency & Supply Chain Security", description: "Track and audit all third-party dependencies for vulnerabilities.", objective: "Prevent supply chain attacks through vulnerable dependencies.", automationLevel: "full", remediationGuidance: "Enable Dependabot or Snyk. Set SLAs for critical vulnerability patching." },
  { controlId: "UCO-CM-005", domain: "Configuration Management", name: "Infrastructure as Code", description: "Manage infrastructure configuration through version-controlled code.", objective: "Ensure consistent, auditable, and reproducible infrastructure.", automationLevel: "partial", remediationGuidance: "Use Terraform, CloudFormation, or Pulumi. Store IaC in version control with code review." },
  { controlId: "UCO-CM-006", domain: "Configuration Management", name: "Change Approval Process", description: "Require approval for all changes to production systems.", objective: "Prevent unauthorized or untested changes from causing incidents.", automationLevel: "partial", remediationGuidance: "Implement change management workflow with approval gates. Log all production changes." },
  { controlId: "UCO-DP-001", domain: "Data Protection", name: "Data Classification Policy", description: "Classify all data by sensitivity level with appropriate handling requirements.", objective: "Apply appropriate security controls based on data sensitivity.", automationLevel: "manual", remediationGuidance: "Define classification tiers (Public, Internal, Confidential, Restricted). Label data accordingly." },
  { controlId: "UCO-DP-002", domain: "Data Protection", name: "Encryption at Rest", description: "Encrypt all sensitive data stored in databases, file systems, and backups.", objective: "Protect data from disclosure in case of storage compromise.", automationLevel: "full", remediationGuidance: "Enable encryption on all databases, S3 buckets, EBS volumes. Use AES-256 minimum." },
  { controlId: "UCO-DP-003", domain: "Data Protection", name: "Encryption in Transit (TLS)", description: "Encrypt all data in transit using TLS 1.2 or higher.", objective: "Prevent interception and tampering of data in transit.", automationLevel: "full", remediationGuidance: "Enforce HTTPS everywhere. Disable TLS 1.0/1.1. Use certificate pinning for critical APIs." },
  { controlId: "UCO-DP-004", domain: "Data Protection", name: "Data Retention & Disposal", description: "Define and enforce data retention schedules and secure disposal procedures.", objective: "Minimize data exposure and ensure regulatory compliance.", automationLevel: "partial", remediationGuidance: "Define retention policy per data type. Automate deletion at end of retention period. Use secure wiping for hardware." },
  { controlId: "UCO-DP-005", domain: "Data Protection", name: "Backup & Recovery Testing", description: "Regularly backup data and test restoration procedures.", objective: "Ensure data can be recovered following loss or ransomware.", automationLevel: "partial", remediationGuidance: "Implement 3-2-1 backup strategy. Test restoration quarterly. Store backups off-site or in different region." },
  { controlId: "UCO-IR-001", domain: "Incident Response", name: "Incident Response Plan", description: "Maintain a documented incident response plan with defined roles and procedures.", objective: "Enable rapid, coordinated response to security incidents.", automationLevel: "manual", remediationGuidance: "Document IR plan covering: detection, containment, eradication, recovery, lessons learned. Test annually." },
  { controlId: "UCO-IR-002", domain: "Incident Response", name: "Incident Detection & Response", description: "Implement tools and processes to detect, triage, and respond to incidents.", objective: "Minimize time to detect and contain security incidents.", automationLevel: "partial", remediationGuidance: "Deploy EDR, SIEM alerting, and on-call procedures. Define severity tiers and response SLAs." },
  { controlId: "UCO-IR-003", domain: "Incident Response", name: "Security Incident Reporting", description: "Define processes for reporting incidents to regulators and affected parties.", objective: "Meet regulatory notification requirements and maintain trust.", automationLevel: "manual", remediationGuidance: "Document breach notification procedures per regulation (72 hours GDPR, FedRAMP 1 hour). Test annually." },
  { controlId: "UCO-IR-004", domain: "Incident Response", name: "Post-Incident Review", description: "Conduct blameless post-mortems after security incidents.", objective: "Learn from incidents to prevent recurrence.", automationLevel: "manual", remediationGuidance: "Conduct PIR within 5 business days. Document timeline, impact, root cause, remediation." },
  { controlId: "UCO-RM-001", domain: "Risk Management", name: "Risk Assessment Process", description: "Conduct regular formal risk assessments across the organization.", objective: "Identify, prioritize, and address security risks proactively.", automationLevel: "manual", remediationGuidance: "Conduct annual risk assessment. Maintain risk register. Review quarterly or after major changes." },
  { controlId: "UCO-RM-002", domain: "Risk Management", name: "Vendor Risk Management", description: "Assess and monitor security posture of third-party vendors.", objective: "Prevent supply chain and vendor-introduced risk.", automationLevel: "partial", remediationGuidance: "Tier vendors by data access and criticality. Complete security questionnaires. Include security in contracts." },
  { controlId: "UCO-RM-003", domain: "Risk Management", name: "Business Continuity Planning", description: "Maintain tested plans for continuing operations during disruptions.", objective: "Minimize downtime and data loss during incidents or disasters.", automationLevel: "manual", remediationGuidance: "Document BCP/DR plans. Define RTOs and RPOs. Test failover annually." },
  { controlId: "UCO-RM-004", domain: "Risk Management", name: "Penetration Testing", description: "Conduct regular third-party penetration tests of systems and applications.", objective: "Identify vulnerabilities before attackers do.", automationLevel: "manual", remediationGuidance: "Conduct annual pentest minimum. Critical systems quarterly. Remediate critical/high within 30 days." },
  { controlId: "UCO-ST-001", domain: "Security Training", name: "Security Awareness Training", description: "Provide annual security awareness training for all employees.", objective: "Reduce human error as a security risk vector.", automationLevel: "partial", remediationGuidance: "Enroll all employees in annual training. Include phishing simulations. Track completion." },
  { controlId: "UCO-ST-002", domain: "Security Training", name: "Role-Specific Security Training", description: "Provide additional security training for high-risk roles (devs, admins, finance).", objective: "Ensure high-risk roles have role-appropriate security skills.", automationLevel: "partial", remediationGuidance: "Identify high-risk roles. Provide targeted training (secure coding for devs, social engineering for finance)." },
  { controlId: "UCO-NS-001", domain: "Network Security", name: "Network Segmentation", description: "Segment networks to isolate sensitive systems and limit lateral movement.", objective: "Contain breaches and protect crown jewel systems.", automationLevel: "partial", remediationGuidance: "Implement VPCs, subnets, and security groups. Isolate production from dev/test environments." },
  { controlId: "UCO-NS-002", domain: "Network Security", name: "Firewall & Perimeter Controls", description: "Deploy and maintain firewall rules restricting unauthorized network access.", objective: "Prevent unauthorized network access to internal systems.", automationLevel: "full", remediationGuidance: "Audit firewall rules quarterly. Deny by default. Remove unused rules. Log denied traffic." },
  { controlId: "UCO-NS-003", domain: "Network Security", name: "Intrusion Detection (IDS/IPS)", description: "Deploy intrusion detection/prevention systems to identify malicious activity.", objective: "Detect and block network-based attacks in real-time.", automationLevel: "full", remediationGuidance: "Deploy IDS/IPS at network perimeter and between segments. Configure alerting for anomalies." },
  { controlId: "UCO-NS-004", domain: "Network Security", name: "Secure Remote Access (VPN/Zero Trust)", description: "Require VPN or Zero Trust access for remote connections to internal systems.", objective: "Secure remote access and prevent unauthorized entry.", automationLevel: "full", remediationGuidance: "Require VPN or Zero Trust (BeyondCorp, Cloudflare Access) for all remote access. Disable direct SSH." },
  { controlId: "UCO-VM-001", domain: "Vulnerability Management", name: "Vulnerability Management Program", description: "Maintain a formal program for identifying and remediating vulnerabilities.", objective: "Systematically reduce exploitable vulnerabilities across the environment.", automationLevel: "partial", remediationGuidance: "Define vulnerability SLAs: critical 24h, high 7d, medium 30d, low 90d. Track to closure." },
  { controlId: "UCO-VM-002", domain: "Vulnerability Management", name: "Patch Management", description: "Apply security patches to all systems within defined SLA windows.", objective: "Prevent exploitation of known vulnerabilities.", automationLevel: "partial", remediationGuidance: "Automate patching where possible. Track patch compliance. Emergency patch process for critical CVEs." },
  { controlId: "UCO-VM-003", domain: "Vulnerability Management", name: "Container & Image Security", description: "Scan container images for vulnerabilities before deployment.", objective: "Prevent known vulnerabilities from reaching production in containers.", automationLevel: "full", remediationGuidance: "Integrate container scanning in CI/CD. Use trusted base images. Run as non-root. No privileged containers." },
];

const FRAMEWORK_MAPPINGS: Array<{ ucoControlId: string; frameworkKey: string; frameworkControlId: string; frameworkControlName: string; customerResponsibility: string; mappingRationale: string }> = [
  // UCO-AI-001: MFA
  { ucoControlId: "UCO-AI-001", frameworkKey: "soc2", frameworkControlId: "CC6.1", frameworkControlName: "Logical and Physical Access Controls - MFA", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.1 requires MFA for logical access to systems and data." },
  { ucoControlId: "UCO-AI-001", frameworkKey: "fedramp", frameworkControlId: "IA-2(1)", frameworkControlName: "Identification and Authentication - MFA for Privileged Accounts", customerResponsibility: "full", mappingRationale: "FedRAMP requires MFA for privileged and non-privileged accounts." },
  { ucoControlId: "UCO-AI-001", frameworkKey: "cmmc-l2", frameworkControlId: "IA.L2-3.5.3", frameworkControlName: "Use Multi-Factor Authentication", customerResponsibility: "full", mappingRationale: "CMMC Level 2 requires MFA for all local and network access." },
  { ucoControlId: "UCO-AI-001", frameworkKey: "iso27001", frameworkControlId: "A.9.4.2", frameworkControlName: "Secure Log-on Procedures", customerResponsibility: "full", mappingRationale: "ISO 27001 A.9.4.2 requires secure log-on procedures including MFA." },
  { ucoControlId: "UCO-AI-001", frameworkKey: "pci-dss", frameworkControlId: "8.4", frameworkControlName: "MFA for All Access to CDE", customerResponsibility: "full", mappingRationale: "PCI DSS v4.0 requires MFA for all access to the cardholder data environment." },
  { ucoControlId: "UCO-AI-001", frameworkKey: "nist-800-53", frameworkControlId: "IA-2(1)", frameworkControlName: "Multi-Factor Authentication - Privileged Accounts", customerResponsibility: "full", mappingRationale: "NIST 800-53 IA-2 requires MFA for privileged and non-privileged accounts." },
  { ucoControlId: "UCO-AI-001", frameworkKey: "hipaa", frameworkControlId: "164.312(d)", frameworkControlName: "Person or Entity Authentication", customerResponsibility: "full", mappingRationale: "HIPAA requires authentication procedures to verify the identity of users." },
  { ucoControlId: "UCO-AI-001", frameworkKey: "gdpr", frameworkControlId: "Art.32", frameworkControlName: "Security of Processing", customerResponsibility: "full", mappingRationale: "GDPR Art.32 requires appropriate technical measures including access controls." },
  { ucoControlId: "UCO-AI-001", frameworkKey: "cis-controls", frameworkControlId: "6.3", frameworkControlName: "Require MFA for Externally-Exposed Applications", customerResponsibility: "full", mappingRationale: "CIS Control 6.3 requires MFA for all externally-exposed applications." },
  // UCO-AI-002: Privileged Account Controls
  { ucoControlId: "UCO-AI-002", frameworkKey: "soc2", frameworkControlId: "CC6.3", frameworkControlName: "Role-Based Access and Least Privilege", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.3 requires restricting privileged access to authorized personnel." },
  { ucoControlId: "UCO-AI-002", frameworkKey: "fedramp", frameworkControlId: "AC-6", frameworkControlName: "Least Privilege", customerResponsibility: "full", mappingRationale: "FedRAMP AC-6 requires least privilege for system functions including privileged accounts." },
  { ucoControlId: "UCO-AI-002", frameworkKey: "nist-800-53", frameworkControlId: "AC-6(1)", frameworkControlName: "Authorize Access to Security Functions", customerResponsibility: "full", mappingRationale: "NIST 800-53 AC-6(1) requires authorizing access to security-relevant functions." },
  { ucoControlId: "UCO-AI-002", frameworkKey: "pci-dss", frameworkControlId: "7.1", frameworkControlName: "Limit Access to System Components", customerResponsibility: "full", mappingRationale: "PCI DSS 7.1 requires limiting access to system components for privileged users." },
  { ucoControlId: "UCO-AI-002", frameworkKey: "cmmc-l2", frameworkControlId: "AC.L2-3.1.6", frameworkControlName: "Non-Privileged Account Use", customerResponsibility: "full", mappingRationale: "CMMC requires using non-privileged accounts for non-security functions." },
  // UCO-AI-003: Password Policy
  { ucoControlId: "UCO-AI-003", frameworkKey: "soc2", frameworkControlId: "CC6.1", frameworkControlName: "Password and Authentication Controls", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.1 requires strong authentication including password controls." },
  { ucoControlId: "UCO-AI-003", frameworkKey: "pci-dss", frameworkControlId: "8.3", frameworkControlName: "Secure Individual Non-Consumer User Accounts", customerResponsibility: "full", mappingRationale: "PCI DSS 8.3 requires secure password/passphrase requirements." },
  { ucoControlId: "UCO-AI-003", frameworkKey: "nist-800-53", frameworkControlId: "IA-5", frameworkControlName: "Authenticator Management", customerResponsibility: "full", mappingRationale: "NIST 800-53 IA-5 requires managing authenticators including password complexity." },
  { ucoControlId: "UCO-AI-003", frameworkKey: "cis-controls", frameworkControlId: "5.2", frameworkControlName: "Use Unique Passwords", customerResponsibility: "full", mappingRationale: "CIS Control 5.2 requires unique, complex passwords for all accounts." },
  // UCO-AI-004: SSO / IdP
  { ucoControlId: "UCO-AI-004", frameworkKey: "soc2", frameworkControlId: "CC6.1", frameworkControlName: "Centralized Authentication", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.1 requires centralized identity management for consistent access control." },
  { ucoControlId: "UCO-AI-004", frameworkKey: "iso27001", frameworkControlId: "A.9.2.1", frameworkControlName: "User Registration and De-registration", customerResponsibility: "full", mappingRationale: "ISO 27001 A.9.2.1 requires a formal user registration process via IdP." },
  { ucoControlId: "UCO-AI-004", frameworkKey: "nist-800-53", frameworkControlId: "IA-8", frameworkControlName: "Identification and Authentication - Non-Organizational Users", customerResponsibility: "full", mappingRationale: "NIST 800-53 IA-8 requires identification and authentication for non-org users via IdP." },
  // UCO-AC-001: RBAC
  { ucoControlId: "UCO-AC-001", frameworkKey: "soc2", frameworkControlId: "CC6.2", frameworkControlName: "Prior to Issuing System Credentials", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.2 requires RBAC with appropriate authorization before granting access." },
  { ucoControlId: "UCO-AC-001", frameworkKey: "fedramp", frameworkControlId: "AC-3", frameworkControlName: "Access Enforcement", customerResponsibility: "full", mappingRationale: "FedRAMP AC-3 enforces access control policies through RBAC." },
  { ucoControlId: "UCO-AC-001", frameworkKey: "cmmc-l2", frameworkControlId: "AC.L2-3.1.1", frameworkControlName: "Authorized Access Control", customerResponsibility: "full", mappingRationale: "CMMC requires limiting system access to authorized users and processes." },
  { ucoControlId: "UCO-AC-001", frameworkKey: "iso27001", frameworkControlId: "A.9.1.1", frameworkControlName: "Access Control Policy", customerResponsibility: "full", mappingRationale: "ISO 27001 A.9.1.1 requires an access control policy based on business needs." },
  { ucoControlId: "UCO-AC-001", frameworkKey: "pci-dss", frameworkControlId: "7.2", frameworkControlName: "Access Control Systems", customerResponsibility: "full", mappingRationale: "PCI DSS 7.2 requires access control systems with deny-all default." },
  { ucoControlId: "UCO-AC-001", frameworkKey: "nist-800-53", frameworkControlId: "AC-2", frameworkControlName: "Account Management", customerResponsibility: "full", mappingRationale: "NIST 800-53 AC-2 requires role-based account management." },
  { ucoControlId: "UCO-AC-001", frameworkKey: "hipaa", frameworkControlId: "164.312(a)(1)", frameworkControlName: "Access Control", customerResponsibility: "full", mappingRationale: "HIPAA requires technical policies for access to ePHI based on roles." },
  // UCO-AC-002: Least Privilege
  { ucoControlId: "UCO-AC-002", frameworkKey: "soc2", frameworkControlId: "CC6.3", frameworkControlName: "Least Privilege Access", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.3 requires access to be restricted to the minimum necessary." },
  { ucoControlId: "UCO-AC-002", frameworkKey: "fedramp", frameworkControlId: "AC-6", frameworkControlName: "Least Privilege", customerResponsibility: "full", mappingRationale: "FedRAMP AC-6 requires least privilege principles." },
  { ucoControlId: "UCO-AC-002", frameworkKey: "nist-800-53", frameworkControlId: "AC-6", frameworkControlName: "Least Privilege", customerResponsibility: "full", mappingRationale: "NIST 800-53 AC-6 requires employing the principle of least privilege." },
  { ucoControlId: "UCO-AC-002", frameworkKey: "cmmc-l2", frameworkControlId: "AC.L2-3.1.5", frameworkControlName: "Least Privilege", customerResponsibility: "full", mappingRationale: "CMMC requires employing the principle of least privilege." },
  // UCO-AC-004: Access Reviews
  { ucoControlId: "UCO-AC-004", frameworkKey: "soc2", frameworkControlId: "CC6.2", frameworkControlName: "User Access Reviews", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.2 requires regular review and recertification of user access." },
  { ucoControlId: "UCO-AC-004", frameworkKey: "iso27001", frameworkControlId: "A.9.2.5", frameworkControlName: "Review of User Access Rights", customerResponsibility: "full", mappingRationale: "ISO 27001 A.9.2.5 requires regular reviews of user access rights." },
  { ucoControlId: "UCO-AC-004", frameworkKey: "hipaa", frameworkControlId: "164.308(a)(3)", frameworkControlName: "Workforce Access Management", customerResponsibility: "full", mappingRationale: "HIPAA requires workforce access management and review." },
  { ucoControlId: "UCO-AC-004", frameworkKey: "pci-dss", frameworkControlId: "7.3", frameworkControlName: "All User Accounts and Access Privileges Are Reviewed", customerResponsibility: "full", mappingRationale: "PCI DSS 7.3 requires reviewing all user accounts and privileges at least every 6 months." },
  // UCO-AC-005: Offboarding
  { ucoControlId: "UCO-AC-005", frameworkKey: "soc2", frameworkControlId: "CC6.2", frameworkControlName: "Access Termination", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.2 requires removing access upon employment termination." },
  { ucoControlId: "UCO-AC-005", frameworkKey: "iso27001", frameworkControlId: "A.7.3.1", frameworkControlName: "Termination or Change of Employment Responsibilities", customerResponsibility: "full", mappingRationale: "ISO 27001 A.7.3.1 requires removing access upon termination." },
  { ucoControlId: "UCO-AC-005", frameworkKey: "nist-800-53", frameworkControlId: "PS-4", frameworkControlName: "Personnel Termination", customerResponsibility: "full", mappingRationale: "NIST 800-53 PS-4 requires deprovisioning access upon personnel termination." },
  // UCO-AL-001: Audit Logging
  { ucoControlId: "UCO-AL-001", frameworkKey: "soc2", frameworkControlId: "CC7.2", frameworkControlName: "Monitor System Components", customerResponsibility: "full", mappingRationale: "SOC 2 CC7.2 requires monitoring system components for anomalies and events." },
  { ucoControlId: "UCO-AL-001", frameworkKey: "fedramp", frameworkControlId: "AU-2", frameworkControlName: "Audit Events", customerResponsibility: "full", mappingRationale: "FedRAMP AU-2 requires defining and auditing security-relevant events." },
  { ucoControlId: "UCO-AL-001", frameworkKey: "hipaa", frameworkControlId: "164.312(b)", frameworkControlName: "Audit Controls", customerResponsibility: "full", mappingRationale: "HIPAA requires hardware, software, and procedural mechanisms to record and examine activity." },
  { ucoControlId: "UCO-AL-001", frameworkKey: "pci-dss", frameworkControlId: "10.2", frameworkControlName: "Implement Audit Logs", customerResponsibility: "full", mappingRationale: "PCI DSS 10.2 requires audit logs for all system components." },
  { ucoControlId: "UCO-AL-001", frameworkKey: "nist-800-53", frameworkControlId: "AU-2", frameworkControlName: "Event Logging", customerResponsibility: "full", mappingRationale: "NIST 800-53 AU-2 requires organizations to determine events to be logged." },
  { ucoControlId: "UCO-AL-001", frameworkKey: "iso27001", frameworkControlId: "A.12.4.1", frameworkControlName: "Event Logging", customerResponsibility: "full", mappingRationale: "ISO 27001 A.12.4.1 requires event logs recording user activities and security events." },
  { ucoControlId: "UCO-AL-001", frameworkKey: "cmmc-l2", frameworkControlId: "AU.L2-3.3.1", frameworkControlName: "System Auditing", customerResponsibility: "full", mappingRationale: "CMMC requires creating and retaining system audit logs." },
  // UCO-AL-002: Log Retention
  { ucoControlId: "UCO-AL-002", frameworkKey: "fedramp", frameworkControlId: "AU-11", frameworkControlName: "Audit Record Retention", customerResponsibility: "full", mappingRationale: "FedRAMP AU-11 requires retaining audit records for 12 months." },
  { ucoControlId: "UCO-AL-002", frameworkKey: "pci-dss", frameworkControlId: "10.7", frameworkControlName: "Retain Audit Log History", customerResponsibility: "full", mappingRationale: "PCI DSS 10.7 requires retaining audit logs for at least 12 months." },
  { ucoControlId: "UCO-AL-002", frameworkKey: "hipaa", frameworkControlId: "164.312(b)", frameworkControlName: "Audit Log Retention", customerResponsibility: "full", mappingRationale: "HIPAA requires retaining audit logs for 6+ years." },
  { ucoControlId: "UCO-AL-002", frameworkKey: "nist-800-53", frameworkControlId: "AU-11", frameworkControlName: "Audit Record Retention", customerResponsibility: "full", mappingRationale: "NIST 800-53 AU-11 requires protecting audit records for a defined retention period." },
  // UCO-AL-003: SIEM
  { ucoControlId: "UCO-AL-003", frameworkKey: "soc2", frameworkControlId: "CC7.2", frameworkControlName: "Security Monitoring", customerResponsibility: "full", mappingRationale: "SOC 2 CC7.2 requires monitoring security events and anomalies." },
  { ucoControlId: "UCO-AL-003", frameworkKey: "fedramp", frameworkControlId: "SI-4", frameworkControlName: "System Monitoring", customerResponsibility: "full", mappingRationale: "FedRAMP SI-4 requires continuous system monitoring for security events." },
  { ucoControlId: "UCO-AL-003", frameworkKey: "nist-800-53", frameworkControlId: "SI-4", frameworkControlName: "System Monitoring", customerResponsibility: "full", mappingRationale: "NIST 800-53 SI-4 requires monitoring systems to detect attacks and anomalies." },
  { ucoControlId: "UCO-AL-003", frameworkKey: "pci-dss", frameworkControlId: "10.6", frameworkControlName: "Review Logs and Security Events", customerResponsibility: "full", mappingRationale: "PCI DSS 10.6 requires reviewing logs and security events daily." },
  // UCO-CM-001: Version Control
  { ucoControlId: "UCO-CM-001", frameworkKey: "soc2", frameworkControlId: "CC8.1", frameworkControlName: "Change Management Process", customerResponsibility: "full", mappingRationale: "SOC 2 CC8.1 requires infrastructure and application changes be authorized." },
  { ucoControlId: "UCO-CM-001", frameworkKey: "fedramp", frameworkControlId: "CM-3", frameworkControlName: "Configuration Change Control", customerResponsibility: "full", mappingRationale: "FedRAMP CM-3 requires documenting, reviewing, and approving configuration changes." },
  { ucoControlId: "UCO-CM-001", frameworkKey: "cmmc-l2", frameworkControlId: "CM.L2-3.4.3", frameworkControlName: "Security Impact Analysis", customerResponsibility: "full", mappingRationale: "CMMC requires analyzing security impact of changes before implementation." },
  // UCO-CM-002: Code Review
  { ucoControlId: "UCO-CM-002", frameworkKey: "soc2", frameworkControlId: "CC8.1", frameworkControlName: "Change Management - Code Review", customerResponsibility: "full", mappingRationale: "SOC 2 CC8.1 requires testing and approval of changes before deployment." },
  { ucoControlId: "UCO-CM-002", frameworkKey: "fedramp", frameworkControlId: "SA-11", frameworkControlName: "Developer Security Testing", customerResponsibility: "full", mappingRationale: "FedRAMP SA-11 requires developer security testing including code review." },
  { ucoControlId: "UCO-CM-002", frameworkKey: "cis-controls", frameworkControlId: "16.1", frameworkControlName: "Establish and Maintain a Secure Application Dev Process", customerResponsibility: "full", mappingRationale: "CIS Control 16 requires secure application development including code review." },
  // UCO-CM-003: SAST/DAST
  { ucoControlId: "UCO-CM-003", frameworkKey: "soc2", frameworkControlId: "CC8.1", frameworkControlName: "Vulnerability Testing", customerResponsibility: "full", mappingRationale: "SOC 2 CC8.1 requires testing for vulnerabilities as part of change management." },
  { ucoControlId: "UCO-CM-003", frameworkKey: "pci-dss", frameworkControlId: "6.3", frameworkControlName: "Identify and Protect from Known Vulnerabilities", customerResponsibility: "full", mappingRationale: "PCI DSS 6.3 requires identifying and protecting all components from known vulnerabilities." },
  { ucoControlId: "UCO-CM-003", frameworkKey: "fedramp", frameworkControlId: "RA-5", frameworkControlName: "Vulnerability Scanning", customerResponsibility: "full", mappingRationale: "FedRAMP RA-5 requires scanning for vulnerabilities in code and applications." },
  // UCO-CM-004: Supply Chain
  { ucoControlId: "UCO-CM-004", frameworkKey: "soc2", frameworkControlId: "CC9.2", frameworkControlName: "Vendor and Business Partner Management", customerResponsibility: "full", mappingRationale: "SOC 2 CC9.2 requires assessing risks from third-party components." },
  { ucoControlId: "UCO-CM-004", frameworkKey: "nist-800-53", frameworkControlId: "SA-12", frameworkControlName: "Supply Chain Protection", customerResponsibility: "full", mappingRationale: "NIST 800-53 SA-12 requires protecting against supply chain threats." },
  { ucoControlId: "UCO-CM-004", frameworkKey: "pci-dss", frameworkControlId: "6.3.3", frameworkControlName: "All Software Is Protected from Known Vulnerabilities", customerResponsibility: "full", mappingRationale: "PCI DSS 6.3.3 requires all system components are protected from known vulnerabilities." },
  // UCO-DP-001: Data Classification
  { ucoControlId: "UCO-DP-001", frameworkKey: "iso27001", frameworkControlId: "A.8.2.1", frameworkControlName: "Classification of Information", customerResponsibility: "full", mappingRationale: "ISO 27001 A.8.2.1 requires classifying information by legal requirements and criticality." },
  { ucoControlId: "UCO-DP-001", frameworkKey: "soc2", frameworkControlId: "CC6.1", frameworkControlName: "Data Classification and Handling", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.1 requires identifying and classifying sensitive data." },
  { ucoControlId: "UCO-DP-001", frameworkKey: "gdpr", frameworkControlId: "Art.30", frameworkControlName: "Records of Processing Activities", customerResponsibility: "full", mappingRationale: "GDPR Art.30 requires maintaining records of processing activities, implying classification." },
  { ucoControlId: "UCO-DP-001", frameworkKey: "nist-800-53", frameworkControlId: "RA-2", frameworkControlName: "Security Categorization", customerResponsibility: "full", mappingRationale: "NIST 800-53 RA-2 requires categorizing information systems by impact level." },
  // UCO-DP-002: Encryption at Rest
  { ucoControlId: "UCO-DP-002", frameworkKey: "soc2", frameworkControlId: "CC6.1", frameworkControlName: "Encryption of Data at Rest", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.1 requires encryption of sensitive data at rest." },
  { ucoControlId: "UCO-DP-002", frameworkKey: "fedramp", frameworkControlId: "SC-28", frameworkControlName: "Protection of Information at Rest", customerResponsibility: "full", mappingRationale: "FedRAMP SC-28 requires protection of information at rest." },
  { ucoControlId: "UCO-DP-002", frameworkKey: "hipaa", frameworkControlId: "164.312(a)(2)(iv)", frameworkControlName: "Encryption and Decryption", customerResponsibility: "full", mappingRationale: "HIPAA addressable implementation specification for encryption of data at rest." },
  { ucoControlId: "UCO-DP-002", frameworkKey: "pci-dss", frameworkControlId: "3.5", frameworkControlName: "Protect Stored Account Data", customerResponsibility: "full", mappingRationale: "PCI DSS 3.5 requires strong cryptography for stored cardholder data." },
  { ucoControlId: "UCO-DP-002", frameworkKey: "nist-800-53", frameworkControlId: "SC-28", frameworkControlName: "Protection of Information at Rest", customerResponsibility: "full", mappingRationale: "NIST 800-53 SC-28 requires encryption of information at rest." },
  { ucoControlId: "UCO-DP-002", frameworkKey: "iso27001", frameworkControlId: "A.10.1.1", frameworkControlName: "Policy on the Use of Cryptographic Controls", customerResponsibility: "full", mappingRationale: "ISO 27001 A.10.1.1 requires a policy on use of cryptographic controls including at-rest encryption." },
  { ucoControlId: "UCO-DP-002", frameworkKey: "gdpr", frameworkControlId: "Art.32(a)", frameworkControlName: "Pseudonymisation and Encryption", customerResponsibility: "full", mappingRationale: "GDPR Art.32 requires encryption as an appropriate technical security measure." },
  // UCO-DP-003: TLS
  { ucoControlId: "UCO-DP-003", frameworkKey: "soc2", frameworkControlId: "CC6.7", frameworkControlName: "Data Transmission Security", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.7 requires encryption of data in transit." },
  { ucoControlId: "UCO-DP-003", frameworkKey: "fedramp", frameworkControlId: "SC-8", frameworkControlName: "Transmission Confidentiality and Integrity", customerResponsibility: "full", mappingRationale: "FedRAMP SC-8 requires protecting data during transmission." },
  { ucoControlId: "UCO-DP-003", frameworkKey: "pci-dss", frameworkControlId: "4.2", frameworkControlName: "Protect PAN Transmissions", customerResponsibility: "full", mappingRationale: "PCI DSS 4.2 requires strong cryptography for all data transmissions." },
  { ucoControlId: "UCO-DP-003", frameworkKey: "hipaa", frameworkControlId: "164.312(e)(2)(ii)", frameworkControlName: "Encryption and Decryption in Transit", customerResponsibility: "full", mappingRationale: "HIPAA requires encryption of ePHI in transit." },
  { ucoControlId: "UCO-DP-003", frameworkKey: "nist-800-53", frameworkControlId: "SC-8", frameworkControlName: "Transmission Confidentiality and Integrity", customerResponsibility: "full", mappingRationale: "NIST 800-53 SC-8 requires protecting the confidentiality of transmitted information." },
  // UCO-DP-004: Data Retention
  { ucoControlId: "UCO-DP-004", frameworkKey: "gdpr", frameworkControlId: "Art.5(1)(e)", frameworkControlName: "Storage Limitation", customerResponsibility: "full", mappingRationale: "GDPR Art.5(1)(e) requires data not be kept longer than necessary." },
  { ucoControlId: "UCO-DP-004", frameworkKey: "hipaa", frameworkControlId: "164.316(b)(2)(i)", frameworkControlName: "Documentation Retention", customerResponsibility: "full", mappingRationale: "HIPAA requires retaining documentation for 6 years." },
  { ucoControlId: "UCO-DP-004", frameworkKey: "iso27001", frameworkControlId: "A.8.3.2", frameworkControlName: "Disposal of Media", customerResponsibility: "full", mappingRationale: "ISO 27001 A.8.3.2 requires secure disposal of media when no longer needed." },
  // UCO-DP-005: Backup & Recovery
  { ucoControlId: "UCO-DP-005", frameworkKey: "soc2", frameworkControlId: "A1.2", frameworkControlName: "Recovery Time and Point Objectives", customerResponsibility: "full", mappingRationale: "SOC 2 A1.2 requires defining and testing RTO/RPO for system recovery." },
  { ucoControlId: "UCO-DP-005", frameworkKey: "fedramp", frameworkControlId: "CP-9", frameworkControlName: "System Backup", customerResponsibility: "full", mappingRationale: "FedRAMP CP-9 requires conducting backups of user-level and system-level information." },
  { ucoControlId: "UCO-DP-005", frameworkKey: "iso27001", frameworkControlId: "A.12.3.1", frameworkControlName: "Information Backup", customerResponsibility: "full", mappingRationale: "ISO 27001 A.12.3.1 requires backup copies of information and testing." },
  { ucoControlId: "UCO-DP-005", frameworkKey: "nist-800-53", frameworkControlId: "CP-9", frameworkControlName: "System Backup", customerResponsibility: "full", mappingRationale: "NIST 800-53 CP-9 requires system backup plans and testing." },
  // UCO-IR-001: IR Plan
  { ucoControlId: "UCO-IR-001", frameworkKey: "soc2", frameworkControlId: "CC7.3", frameworkControlName: "Evaluate Security Events", customerResponsibility: "full", mappingRationale: "SOC 2 CC7.3 requires evaluating security events and implementing IR procedures." },
  { ucoControlId: "UCO-IR-001", frameworkKey: "fedramp", frameworkControlId: "IR-1", frameworkControlName: "Incident Response Policy and Procedures", customerResponsibility: "full", mappingRationale: "FedRAMP IR-1 requires formal IR policy and procedures." },
  { ucoControlId: "UCO-IR-001", frameworkKey: "hipaa", frameworkControlId: "164.308(a)(6)", frameworkControlName: "Security Incident Procedures", customerResponsibility: "full", mappingRationale: "HIPAA requires implementing policies to address security incidents." },
  { ucoControlId: "UCO-IR-001", frameworkKey: "iso27001", frameworkControlId: "A.16.1.1", frameworkControlName: "Responsibilities and Procedures", customerResponsibility: "full", mappingRationale: "ISO 27001 A.16.1.1 requires establishing IR responsibilities and procedures." },
  { ucoControlId: "UCO-IR-001", frameworkKey: "nist-800-53", frameworkControlId: "IR-1", frameworkControlName: "Incident Response Policy and Procedures", customerResponsibility: "full", mappingRationale: "NIST 800-53 IR-1 requires an incident response policy." },
  { ucoControlId: "UCO-IR-001", frameworkKey: "pci-dss", frameworkControlId: "12.10", frameworkControlName: "Implement an Incident Response Plan", customerResponsibility: "full", mappingRationale: "PCI DSS 12.10 requires a documented and tested incident response plan." },
  { ucoControlId: "UCO-IR-001", frameworkKey: "cmmc-l2", frameworkControlId: "IR.L2-3.6.1", frameworkControlName: "Incident Response Capability", customerResponsibility: "full", mappingRationale: "CMMC requires establishing an operational incident-handling capability." },
  // UCO-IR-003: Breach Notification
  { ucoControlId: "UCO-IR-003", frameworkKey: "gdpr", frameworkControlId: "Art.33", frameworkControlName: "Notification to Supervisory Authority", customerResponsibility: "full", mappingRationale: "GDPR Art.33 requires notifying supervisory authority within 72 hours of a breach." },
  { ucoControlId: "UCO-IR-003", frameworkKey: "hipaa", frameworkControlId: "164.408", frameworkControlName: "Notification to HHS", customerResponsibility: "full", mappingRationale: "HIPAA requires notifying HHS of breaches affecting 500+ individuals within 60 days." },
  { ucoControlId: "UCO-IR-003", frameworkKey: "fedramp", frameworkControlId: "IR-6", frameworkControlName: "Incident Reporting", customerResponsibility: "full", mappingRationale: "FedRAMP IR-6 requires reporting incidents to US-CERT within 1 hour." },
  // UCO-RM-001: Risk Assessment
  { ucoControlId: "UCO-RM-001", frameworkKey: "soc2", frameworkControlId: "CC3.1", frameworkControlName: "Risk Assessment", customerResponsibility: "full", mappingRationale: "SOC 2 CC3.1 requires identifying risks to achieving objectives." },
  { ucoControlId: "UCO-RM-001", frameworkKey: "fedramp", frameworkControlId: "RA-3", frameworkControlName: "Risk Assessment", customerResponsibility: "full", mappingRationale: "FedRAMP RA-3 requires conducting risk assessments." },
  { ucoControlId: "UCO-RM-001", frameworkKey: "iso27001", frameworkControlId: "6.1.2", frameworkControlName: "Information Security Risk Assessment", customerResponsibility: "full", mappingRationale: "ISO 27001 requires periodic information security risk assessments." },
  { ucoControlId: "UCO-RM-001", frameworkKey: "nist-800-53", frameworkControlId: "RA-3", frameworkControlName: "Risk Assessment", customerResponsibility: "full", mappingRationale: "NIST 800-53 RA-3 requires risk assessments for information systems." },
  { ucoControlId: "UCO-RM-001", frameworkKey: "hipaa", frameworkControlId: "164.308(a)(1)", frameworkControlName: "Risk Analysis", customerResponsibility: "full", mappingRationale: "HIPAA requires conducting accurate and thorough risk analysis." },
  { ucoControlId: "UCO-RM-001", frameworkKey: "cmmc-l2", frameworkControlId: "RA.L2-3.11.1", frameworkControlName: "Risk Assessments", customerResponsibility: "full", mappingRationale: "CMMC requires periodically assessing the risk to organizational operations." },
  // UCO-RM-002: Vendor Risk
  { ucoControlId: "UCO-RM-002", frameworkKey: "soc2", frameworkControlId: "CC9.2", frameworkControlName: "Vendor and Business Partner Risk Management", customerResponsibility: "full", mappingRationale: "SOC 2 CC9.2 requires assessing third-party risks and monitoring compliance." },
  { ucoControlId: "UCO-RM-002", frameworkKey: "iso27001", frameworkControlId: "A.15.1.1", frameworkControlName: "Information Security Policy for Supplier Relationships", customerResponsibility: "full", mappingRationale: "ISO 27001 A.15.1.1 requires information security requirements for supplier relationships." },
  { ucoControlId: "UCO-RM-002", frameworkKey: "gdpr", frameworkControlId: "Art.28", frameworkControlName: "Processor Agreements", customerResponsibility: "full", mappingRationale: "GDPR Art.28 requires data processing agreements with all processors." },
  // UCO-RM-003: BCP
  { ucoControlId: "UCO-RM-003", frameworkKey: "soc2", frameworkControlId: "A1.3", frameworkControlName: "Business Continuity and Disaster Recovery", customerResponsibility: "full", mappingRationale: "SOC 2 A1.3 requires tested recovery procedures to restore availability." },
  { ucoControlId: "UCO-RM-003", frameworkKey: "iso27001", frameworkControlId: "A.17.1.1", frameworkControlName: "Planning Information Security Continuity", customerResponsibility: "full", mappingRationale: "ISO 27001 A.17.1.1 requires planning for information security continuity." },
  { ucoControlId: "UCO-RM-003", frameworkKey: "fedramp", frameworkControlId: "CP-2", frameworkControlName: "Contingency Plan", customerResponsibility: "full", mappingRationale: "FedRAMP CP-2 requires developing and maintaining a contingency plan." },
  { ucoControlId: "UCO-RM-003", frameworkKey: "nist-800-53", frameworkControlId: "CP-2", frameworkControlName: "Contingency Plan", customerResponsibility: "full", mappingRationale: "NIST 800-53 CP-2 requires a contingency plan for system disruptions." },
  // UCO-RM-004: Penetration Testing
  { ucoControlId: "UCO-RM-004", frameworkKey: "soc2", frameworkControlId: "CC7.1", frameworkControlName: "Penetration Testing", customerResponsibility: "full", mappingRationale: "SOC 2 CC7.1 requires periodic penetration testing." },
  { ucoControlId: "UCO-RM-004", frameworkKey: "pci-dss", frameworkControlId: "11.4", frameworkControlName: "External and Internal Penetration Testing", customerResponsibility: "full", mappingRationale: "PCI DSS 11.4 requires penetration testing at least annually." },
  { ucoControlId: "UCO-RM-004", frameworkKey: "fedramp", frameworkControlId: "CA-8", frameworkControlName: "Penetration Testing", customerResponsibility: "full", mappingRationale: "FedRAMP CA-8 requires penetration testing for systems." },
  // UCO-ST-001: Security Training
  { ucoControlId: "UCO-ST-001", frameworkKey: "soc2", frameworkControlId: "CC1.4", frameworkControlName: "Commitment to Competence", customerResponsibility: "full", mappingRationale: "SOC 2 CC1.4 requires security awareness and training for personnel." },
  { ucoControlId: "UCO-ST-001", frameworkKey: "fedramp", frameworkControlId: "AT-2", frameworkControlName: "Literacy Training and Awareness", customerResponsibility: "full", mappingRationale: "FedRAMP AT-2 requires security awareness training for all personnel." },
  { ucoControlId: "UCO-ST-001", frameworkKey: "hipaa", frameworkControlId: "164.308(a)(5)", frameworkControlName: "Security Awareness and Training", customerResponsibility: "full", mappingRationale: "HIPAA requires security awareness and training program for all workforce members." },
  { ucoControlId: "UCO-ST-001", frameworkKey: "cmmc-l2", frameworkControlId: "AT.L2-3.2.1", frameworkControlName: "Role-Based Risk Awareness", customerResponsibility: "full", mappingRationale: "CMMC requires awareness of security risks associated with user activities." },
  { ucoControlId: "UCO-ST-001", frameworkKey: "iso27001", frameworkControlId: "A.7.2.2", frameworkControlName: "Information Security Awareness, Education and Training", customerResponsibility: "full", mappingRationale: "ISO 27001 A.7.2.2 requires security awareness education for all employees." },
  { ucoControlId: "UCO-ST-001", frameworkKey: "pci-dss", frameworkControlId: "12.6", frameworkControlName: "Security Awareness Program", customerResponsibility: "full", mappingRationale: "PCI DSS 12.6 requires a formal security awareness program for all personnel." },
  { ucoControlId: "UCO-ST-001", frameworkKey: "nist-800-53", frameworkControlId: "AT-2", frameworkControlName: "Literacy Training and Awareness", customerResponsibility: "full", mappingRationale: "NIST 800-53 AT-2 requires security awareness training." },
  // UCO-ST-002: Role-Specific Training
  { ucoControlId: "UCO-ST-002", frameworkKey: "fedramp", frameworkControlId: "AT-3", frameworkControlName: "Role-Based Training", customerResponsibility: "full", mappingRationale: "FedRAMP AT-3 requires role-based security training for personnel with security responsibilities." },
  { ucoControlId: "UCO-ST-002", frameworkKey: "nist-800-53", frameworkControlId: "AT-3", frameworkControlName: "Role-Based Training", customerResponsibility: "full", mappingRationale: "NIST 800-53 AT-3 requires role-based security training." },
  { ucoControlId: "UCO-ST-002", frameworkKey: "cmmc-l2", frameworkControlId: "AT.L2-3.2.2", frameworkControlName: "Role-Based Security Training", customerResponsibility: "full", mappingRationale: "CMMC requires ensuring personnel are trained on security responsibilities." },
  // UCO-VM-001: Vuln Management
  { ucoControlId: "UCO-VM-001", frameworkKey: "soc2", frameworkControlId: "CC7.1", frameworkControlName: "Vulnerability Management", customerResponsibility: "full", mappingRationale: "SOC 2 CC7.1 requires identification and management of vulnerabilities." },
  { ucoControlId: "UCO-VM-001", frameworkKey: "fedramp", frameworkControlId: "RA-5", frameworkControlName: "Vulnerability Monitoring and Scanning", customerResponsibility: "full", mappingRationale: "FedRAMP RA-5 requires regular vulnerability scanning." },
  { ucoControlId: "UCO-VM-001", frameworkKey: "pci-dss", frameworkControlId: "11.3", frameworkControlName: "External Vulnerability Scans", customerResponsibility: "full", mappingRationale: "PCI DSS 11.3 requires quarterly vulnerability scans." },
  { ucoControlId: "UCO-VM-001", frameworkKey: "iso27001", frameworkControlId: "A.12.6.1", frameworkControlName: "Management of Technical Vulnerabilities", customerResponsibility: "full", mappingRationale: "ISO 27001 A.12.6.1 requires timely identification and remediation of vulnerabilities." },
  { ucoControlId: "UCO-VM-001", frameworkKey: "nist-800-53", frameworkControlId: "RA-5", frameworkControlName: "Vulnerability Monitoring and Scanning", customerResponsibility: "full", mappingRationale: "NIST 800-53 RA-5 requires scanning for vulnerabilities." },
  // UCO-VM-002: Patch Management
  { ucoControlId: "UCO-VM-002", frameworkKey: "soc2", frameworkControlId: "CC7.1", frameworkControlName: "Patch Management", customerResponsibility: "full", mappingRationale: "SOC 2 CC7.1 requires patch management as part of vulnerability management." },
  { ucoControlId: "UCO-VM-002", frameworkKey: "fedramp", frameworkControlId: "SI-2", frameworkControlName: "Flaw Remediation", customerResponsibility: "full", mappingRationale: "FedRAMP SI-2 requires identifying, reporting, and correcting system flaws." },
  { ucoControlId: "UCO-VM-002", frameworkKey: "cmmc-l2", frameworkControlId: "SI.L2-3.14.1", frameworkControlName: "Identify and Manage Information System Flaws", customerResponsibility: "full", mappingRationale: "CMMC requires identifying and patching system flaws." },
  { ucoControlId: "UCO-VM-002", frameworkKey: "pci-dss", frameworkControlId: "6.3.3", frameworkControlName: "All Software Protected from Known Vulnerabilities", customerResponsibility: "full", mappingRationale: "PCI DSS 6.3.3 requires patching all system components." },
  { ucoControlId: "UCO-VM-002", frameworkKey: "nist-800-53", frameworkControlId: "SI-2", frameworkControlName: "Flaw Remediation", customerResponsibility: "full", mappingRationale: "NIST 800-53 SI-2 requires identifying and correcting system flaws." },
  // UCO-NS-001: Network Segmentation
  { ucoControlId: "UCO-NS-001", frameworkKey: "soc2", frameworkControlId: "CC6.6", frameworkControlName: "Network Security Controls", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.6 requires network security measures including segmentation." },
  { ucoControlId: "UCO-NS-001", frameworkKey: "fedramp", frameworkControlId: "SC-7", frameworkControlName: "Boundary Protection", customerResponsibility: "full", mappingRationale: "FedRAMP SC-7 requires boundary protection through network segmentation." },
  { ucoControlId: "UCO-NS-001", frameworkKey: "pci-dss", frameworkControlId: "1.3", frameworkControlName: "Network Access Controls", customerResponsibility: "full", mappingRationale: "PCI DSS 1.3 requires network access controls and segmentation for CDE." },
  { ucoControlId: "UCO-NS-001", frameworkKey: "nist-800-53", frameworkControlId: "SC-7", frameworkControlName: "Boundary Protection", customerResponsibility: "full", mappingRationale: "NIST 800-53 SC-7 requires boundary protection and network segmentation." },
  { ucoControlId: "UCO-NS-001", frameworkKey: "iso27001", frameworkControlId: "A.13.1.3", frameworkControlName: "Segregation in Networks", customerResponsibility: "full", mappingRationale: "ISO 27001 A.13.1.3 requires segregation of groups of information services." },
  // UCO-NS-002: Firewall
  { ucoControlId: "UCO-NS-002", frameworkKey: "soc2", frameworkControlId: "CC6.6", frameworkControlName: "Firewall Controls", customerResponsibility: "full", mappingRationale: "SOC 2 CC6.6 requires firewall and perimeter security controls." },
  { ucoControlId: "UCO-NS-002", frameworkKey: "pci-dss", frameworkControlId: "1.2", frameworkControlName: "Firewall Configuration Standards", customerResponsibility: "full", mappingRationale: "PCI DSS 1.2 requires restricting inbound and outbound traffic to necessary communication." },
  { ucoControlId: "UCO-NS-002", frameworkKey: "fedramp", frameworkControlId: "SC-7", frameworkControlName: "Boundary Protection - Firewall", customerResponsibility: "full", mappingRationale: "FedRAMP SC-7 includes firewall controls as part of boundary protection." },
  // UCO-NS-004: VPN/Zero Trust
  { ucoControlId: "UCO-NS-004", frameworkKey: "fedramp", frameworkControlId: "AC-17", frameworkControlName: "Remote Access", customerResponsibility: "full", mappingRationale: "FedRAMP AC-17 requires establishing usage restrictions for remote access." },
  { ucoControlId: "UCO-NS-004", frameworkKey: "nist-800-53", frameworkControlId: "AC-17", frameworkControlName: "Remote Access", customerResponsibility: "full", mappingRationale: "NIST 800-53 AC-17 requires protecting and controlling remote access sessions." },
  { ucoControlId: "UCO-NS-004", frameworkKey: "cmmc-l2", frameworkControlId: "AC.L2-3.1.12", frameworkControlName: "Control Remote Access Sessions", customerResponsibility: "full", mappingRationale: "CMMC requires controlling and monitoring remote access sessions." },
  { ucoControlId: "UCO-NS-004", frameworkKey: "iso27001", frameworkControlId: "A.6.2.2", frameworkControlName: "Teleworking", customerResponsibility: "full", mappingRationale: "ISO 27001 A.6.2.2 requires a policy and supporting security measures for teleworking." },
];

const AUTOMATED_TESTS = [
  { ucoControlId: "UCO-AI-001", testKey: "github-mfa-required", name: "GitHub Organization MFA Enforcement", description: "Checks if MFA is required for all members of the GitHub organization.", requiredIntegration: "github", testLogic: "GET /orgs/{org} → check two_factor_requirement_enabled", passCriteria: "two_factor_requirement_enabled === true", severity: "critical" },
  { ucoControlId: "UCO-CM-001", testKey: "github-repos-exist", name: "GitHub Version Control Usage", description: "Confirms code is stored in GitHub version control.", requiredIntegration: "github", testLogic: "GET /user/repos → count > 0", passCriteria: "At least one repository exists", severity: "medium" },
  { ucoControlId: "UCO-CM-002", testKey: "github-branch-protection", name: "GitHub Branch Protection Enabled", description: "Checks if default branches have protection rules enabled.", requiredIntegration: "github", testLogic: "GET /repos/{owner}/{repo}/branches/{branch} → check protection.enabled", passCriteria: ">=70% of sampled repos have branch protection enabled", severity: "high" },
  { ucoControlId: "UCO-CM-002", testKey: "github-required-reviews", name: "GitHub Required PR Reviews", description: "Checks if pull request reviews are required before merging.", requiredIntegration: "github", testLogic: "GET /repos/{owner}/{repo}/branches/{branch} → check required_pull_request_reviews", passCriteria: ">=50% of sampled repos require PR reviews", severity: "high" },
  { ucoControlId: "UCO-CM-003", testKey: "github-dependabot-alerts", name: "GitHub Dependabot Vulnerability Alerts", description: "Checks if Dependabot alerts are enabled for vulnerability detection.", requiredIntegration: "github", testLogic: "GET /repos/{owner}/{repo}/vulnerability-alerts", passCriteria: ">=50% of repos have vulnerability alerts enabled", severity: "high" },
  { ucoControlId: "UCO-AC-004", testKey: "github-team-membership-reviewed", name: "GitHub Team Access Reviewed", description: "Checks if teams and outside collaborators have been audited.", requiredIntegration: "github", testLogic: "GET /orgs/{org}/teams and /orgs/{org}/outside_collaborators", passCriteria: "Organization has defined teams with reviewed membership", severity: "medium" },
];

async function seed() {
  console.log("Seeding UCO controls...");
  for (const control of UCO_CONTROLS) {
    await db.insert(ucoControlsTable).values(control).onConflictDoNothing();
  }
  console.log(`Seeded ${UCO_CONTROLS.length} UCO controls.`);

  console.log("Seeding framework mappings...");
  for (const mapping of FRAMEWORK_MAPPINGS) {
    await db.insert(ucoFrameworkMappingsTable).values(mapping).onConflictDoNothing();
  }
  console.log(`Seeded ${FRAMEWORK_MAPPINGS.length} framework mappings.`);

  console.log("Seeding automated tests...");
  for (const test of AUTOMATED_TESTS) {
    await db.insert(ucoAutomatedTestsTable).values(test).onConflictDoNothing();
  }
  console.log(`Seeded ${AUTOMATED_TESTS.length} automated tests.`);

  console.log("Seed complete!");
  process.exit(0);
}

seed().catch(err => { console.error(err); process.exit(1); });
